# Site settings
title: Krishna Heroor Portfolio
description: A website about my all projects and profiles
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hey! I'm Krishna Heroor
user_description: Engineer by Profession ğŸ‘¨â€ğŸ’» Writer by passionâœï¸.
user_title: Machine Learning Practitioner
email: heroorkrishna@gmail.com
twitter_username: krishnaheroor
github_username:  heroorkrishna
# facebook_username: Krishnaheroor 
linkedin_username: Krishnaheroor
instagram_username: _krishnaheroor_
buymecoffee_username: krishnaheroor

# Google-analytics
google-analytics:
  id: "UA-120517137-1"

exclude: ['package.json', 'src' , 'node_modules']
